services:
  discord-bot:
    image: orpheus-discord-bot
    build:
      context: ./discord-bot
      dockerfile: Dockerfile
    volumes:
      - ./discord-bot:/app
    env_file:
      - .env
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - .env

  audio-player:
    build:
      context: ./audio-player
      dockerfile: Dockerfile
    volumes:
      - ./audio-player:/app
      - /app/node_modules
    ports:
      - "3001:3000"
    env_file:
      - .env
    depends_on:
      - backend 