# Development configuration
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"  # Flask server port
      - "3000:3000"  # Frontend dev server port
    volumes:
      # Development volumes for hot reloading
      - ./audio_processing:/app/audio_processing
      - ./discord_bot:/app/discord_bot
      - ./frontend/src:/app/frontend/src:cached
      - ./frontend/public:/app/frontend/public:cached
      # Exclude node_modules from volume mount
      - /app/frontend/node_modules
      # Persist data
      - ./audio_processing/data:/app/audio_processing/data
      # Don't override the static files from the frontend build
      - /app/audio_processing/static
    environment:
      - NODE_ENV=development
      - PYTHONUNBUFFERED=1  # Better Python logging
      - DISCORD_TOKEN=${DISCORD_TOKEN}  # Pass through from host environment
      - CHOKIDAR_USEPOLLING=true  # Enable file watching
      - WATCHPACK_POLLING=true    # Enable webpack polling
      - WDS_SOCKET_PORT=3000      # WebSocket port for hot reload
      - REACT_APP_API_URL=http://localhost:5000/api  # API URL for frontend
      - FLASK_ENV=development     # Enable Flask development mode
      - FLASK_APP=app.py          # Specify Flask application file
    env_file:
      - .env  # Alternative: load from .env file
    stdin_open: true  # Required for react-scripts start
    tty: true        # Required for react-scripts start
    restart: unless-stopped 