# Development configuration
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      # Development volumes for hot reloading
      - ./audio-processing:/app/audio-processing
      - ./discord-bot:/app/discord-bot
      # Persist data
      - ./audio-processing/data:/app/audio-processing/data
      # Don't override the static files from the frontend build
      - /app/audio-processing/static
    environment:
      - NODE_ENV=development
      - PYTHONUNBUFFERED=1  # Better Python logging
      - DISCORD_TOKEN=${DISCORD_TOKEN}  # Pass through from host environment
    env_file:
      - .env  # Alternative: load from .env file
    restart: unless-stopped 